spring:
  application:
    name: product-service
  profiles:
    active: dev
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:product-db}
      host: ${MONGO_HOST:localhost}