version: "3.8"
services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    networks:
      backend:
        aliases:
          - "postgres"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      backend:
        aliases:
          - "mongo"

  config-server:
    container_name: config-server
    image: umutulasgul/config-server
    ports:
      - "8888:8888"
    networks:
      backend:
        aliases:
          - "config-server"

  eureka-server:
    container_name: eureka-server
    image: umutulasgul/eureka-server
    ports:
      - "8761:8761"
    environment:
      APPLICATION_NAME: "eureka-server"
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIG_SERVER_ENABLED: "true"
      CONFIG_SERVER_HOST: "config-server"
      CONFIG_SERVER_PORT: "8888"
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eureka-server"

  api-gateway:
    container_name: api-gateway
    image: umutulasgul/api-gateway
    ports:
      - "8000:8000"
    environment:
      APPLICATION_NAME: "api-gateway"
      CONFIG_SERVER_HOST: "config-server"
      CONFIG_SERVER_PORT: "8888"
      REGISTRY_HOST: "eureka-server"
      REGISTRY_PORT: "8761"
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "api-gateway"

  product-service:
    container_name: product-service
    image: umutulasgul/product-service
    ports:
      - "8001:8001"
    environment:
      APPLICATION_NAME: "product-service"
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIG_SERVER_ENABLED: "true"
      CONFIG_SERVER_HOST: "config-server"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_CLIENT_ENABLED: "true"
      REGISTRY_HOST: "eureka-server"
      REGISTRY_PORT: "8761"
      GATEWAY_HOST: "api-gateway"
      GATEWAY_PORT: "8000"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "product-db"
    depends_on:
      mongo:
        condition: service_started
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      backend:
        aliases:
          - "product-service"

  customer-service:
    container_name: customer-service
    image: umutulasgul/customer-service
    ports:
      - "8002:8002"
    environment:
      APPLICATION_NAME: "customer-service"
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIG_SERVER_HOST: "config-server"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_CLIENT_ENABLED: "true"
      REGISTRY_HOST: "eureka-server"
      REGISTRY_PORT: "8761"
      GATEWAY_HOST: "api-gateway"
      GATEWAY_PORT: "8000"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "customer-db"
    depends_on:
      postgres:
        condition: service_started
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started

    networks:
      backend:
        aliases:
          - "customer-service"

  order-service:
    container_name: order-service
    image: umutulasgul/order-service
    ports:
      - "8003:8003"
    environment:
      APPLICATION_NAME: "order-service"
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIG_SERVER_ENABLED: "true"
      CONFIG_SERVER_HOST: "config-server"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_CLIENT_ENABLED: "true"
      REGISTRY_HOST: "eureka-server"
      REGISTRY_PORT: "8761"
      GATEWAY_HOST: "api-gateway"
      GATEWAY_PORT: "8000"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "order-db"
    depends_on:
      postgres:
        condition: service_started
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      backend:
        aliases:
          - "order-service"

networks:
  backend:
    driver: bridge